name       : python-userpath
version    : 1.7.0
release    : 2
source     :
    - https://github.com/ofek/userpath/archive/refs/tags/1.7.0.tar.gz : 38c9652054d1eddaeab27c3ac8f2cdfb60afdfd23a37dc58cf6dbb748a65b25c
license    :
    - Apache-2.0
    - MIT
component  : programming.python
summary    : Cross-platform tool for adding locations to the user PATH, no elevated privileges required!
description: |
    Cross-platform tool for adding locations to the user PATH, no elevated privileges required!
rundeps    :
    - python-click
build      : |
    %python3_setup
install    : |
    %python3_install
